spring:
  application:
    name: ExamTask
  datasource:
    driver-class-name: org.postgresql.Driver
    password: "admin"
    username: "postgres"
    url: "jdbc:postgresql://localhost:5432/exam_task"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


